# ===========================================================================
# Project:   Xmms
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :iweb, :required => [:sproutcore, :"sproutcore/animation"]
config :demo, :required => [:sproutcore, :iweb], :theme => "sproutcore/ace", :css_theme => "ace.demo"

config :carrousel, :required => [:sproutcore, :iweb], :theme => "sproutcore/ace", :css_theme => "ace.carrousel"